#
# Copyright (c) Microsoft Corporation
# Licensed under the MIT License.
#

name: caf_landing_zones_github_actions

on:
  push:
    branches:
      - master
      - vnext
  pull_request:
    branches:
      - master
      - vnext

jobs:
  tfsec:
    name: Run TFsec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Terraform security scan
        uses: triat/terraform-security-scan@v2.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

